#!/usr/bin/env python3
"""Regenerate _data/img_dims.yml: every JPEG under assets/images, path -> [w,h].

Run after adding or replacing photographs:

    python3 _scripts/gen-img-dims.py

Why it exists: an <img> with no width/height reserves no space, so the page
reflows as each photograph arrives. On a 30-photo wedding gallery that is the
whole page moving under the reader. Jekyll can't measure a file, so the sizes
are measured once, here, and the templates read them out of this data file.

Reads the JPEG SOF marker directly; no third-party imaging library.
"""
import struct, glob, yaml, os

def jpeg_size(path):
    with open(path, 'rb') as f:
        if f.read(2) != b'\xff\xd8':
            return None
        while True:
            b = f.read(1)
            while b and b != b'\xff':
                b = f.read(1)
            while b == b'\xff':
                b = f.read(1)
            if not b:
                return None
            marker = b[0]
            # SOF0-SOF15, excluding the DHT/JPG/DAC markers interleaved with them
            if marker in (0xC0,0xC1,0xC2,0xC3,0xC5,0xC6,0xC7,0xC9,0xCA,0xCB,0xCD,0xCE,0xCF):
                f.read(3)
                h, w = struct.unpack('>HH', f.read(4))
                return w, h
            length = struct.unpack('>H', f.read(2))[0]
            f.seek(length - 2, 1)

root = os.path.join(os.path.dirname(__file__), '..')
os.chdir(root)
dims = {}
for p in sorted(glob.glob('assets/images/**/*.jpg', recursive=True)):
    try:
        s = jpeg_size(p)
    except Exception:
        s = None
    if s:
        dims['/' + p] = list(s)

with open('_data/img_dims.yml', 'w') as f:
    f.write("# Intrinsic pixel size of every JPEG under assets/images, path -> [w, h].\n"
            "# Generated by _scripts/gen-img-dims.py; regenerate after adding photos.\n"
            "# It exists so every <img> can carry width/height and reserve its space,\n"
            "# instead of the page reflowing as each photograph arrives.\n")
    yaml.safe_dump(dims, f, default_flow_style=True, width=200)
print(f'measured {len(dims)} images -> _data/img_dims.yml')
